### ISSUE TITLE
[Feat]: Creada Estructura del Proyecto

### ISSUE THREAD

**Issue by linuxmobile** [GeraAlcantara/Votaciones_Premios_Front_end#12]
### Descripción:

Creada estructura general del proyecto Next.js. Tomando como guía [este post de Dev.To](https://dev.to/josemukorivo/how-i-approach-and-structure-enterprise-frontend-applications-after-4-years-of-using-nextjs-2f5)

**Comment by descorce** [comment]
Deseo proponer cambios para la estructura del proyecto, patrones de diseño y tecnologias a usar, si es posible que me asignen tambien a esta tarea.
