### ISSUE TITLE
[Improvements] Crear Licencia y Código de conducta

### ISSUE THREAD

**Issue by linuxmobile** [GeraAlcantara/Votaciones_Premios_Front_end#3]
### Descripción: 

**Código de Conducta:**

El Código de Conducta es esencial para guiar el comportamiento de los contribuidores en nuestro proyecto. Debe establecer las normas y expectativas para la comunicación y la colaboración. Esto incluye, pero no se limita a, cómo interactuar en las discusiones, cómo presentar pull requests y cómo resolver conflictos. Un Código de Conducta claro y respetuoso contribuye a un ambiente saludable y productivo para todos los miembros de la comunidad.

**Licencia GNU:**

La Licencia GNU (GNU General Public License) es un componente legal crucial para nuestro proyecto. Define cómo se pueden usar, modificar y distribuir nuestros activos y código fuente. Además, asegura que los derechos de autor y la propiedad intelectual estén protegidos. 

#### Tareas Pendientes:

- [ ] Crear y publicar una Licencia GNU para nuestro proyecto.
- [ ] Establecer un Código de Conducta que defina las expectativas de comportamiento de los contribuidores.
  
¡Una vez que estas tareas estén completadas, podremos dar por finalizada esta Issue y avanzar con la protección legal y la promoción de un ambiente colaborativo en nuestro proyecto!

**Comment by GeraAlcantara** [comment]
Done
