### ISSUE TITLE
[Request] Creación de Header con Navegación Responsiva

### ISSUE THREAD

**Issue by linuxmobile** [GeraAlcantara/Votaciones_Premios_Front_end#6]
### Descripción:

_Esta issue tiene como objetivo diseñar e implementar un header responsive que proporcione una experiencia de usuario fluida en dispositivos móviles y de escritorio._

**Objetivo:**

- Diseñar y desarrollar un header con navegación que se adapte de forma óptima a diferentes tamaños de pantalla.
- Asegurar que la navegación sea intuitiva y fácil de usar tanto en dispositivos móviles como en escritorio.

**Comment by descorce** [comment]
i'm in
