### ISSUE TITLE
[Request] Implementar el Dark & Light mode

### ISSUE THREAD

**Issue by linuxmobile** [GeraAlcantara/Votaciones_Premios_Front_end#7]
### Descripción:

_Objetivo diseñar e implementar la funcionalidad de dark & light mode para mejorar la experiencia del usuario y brindar opciones de accesibilidad._

Objetivo:

- Diseñar e implementar dark & light mode que sean accesibles y atractivos visualmente. (Con animación/transición adecuada).
- Proporcionar a los usuarios la opción de cambiar entre los modos de acuerdo con sus preferencias.

**Comment by informaticadiaz** [comment]
Voy a estudiar esta solución 

https://dark-mode-nextjs-tailwind-tau.vercel.app/

Este es el repositorio.

https://github.com/losarcosdev/dark-mode-nextjs-tailwind

Una vez implementada la solución en el código lo hago saber.
